// This file will be auto-generated by Supabase CLI
// For now, we define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          date_of_birth: string | null
          gender: string | null
          height_cm: number | null
          target_weight_kg: number | null
          target_calories: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          date_of_birth?: string | null
          gender?: string | null
          height_cm?: number | null
          target_weight_kg?: number | null
          target_calories?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          date_of_birth?: string | null
          gender?: string | null
          height_cm?: number | null
          target_weight_kg?: number | null
          target_calories?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      workouts: {
        Row: {
          id: string
          user_id: string
          date: string
          type: string
          duration_minutes: number
          distance_km: number | null
          calories_burned: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          type: string
          duration_minutes: number
          distance_km?: number | null
          calories_burned?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          type?: string
          duration_minutes?: number
          distance_km?: number | null
          calories_burned?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      meals: {
        Row: {
          id: string
          user_id: string
          date: string
          meal_type: string
          food_name: string
          portion: string | null
          calories: number
          protein_g: number | null
          carbs_g: number | null
          fat_g: number | null
          image_url: string | null
          ai_estimated: boolean | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          meal_type: string
          food_name: string
          portion?: string | null
          calories: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          image_url?: string | null
          ai_estimated?: boolean | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          meal_type?: string
          food_name?: string
          portion?: string | null
          calories?: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          image_url?: string | null
          ai_estimated?: boolean | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      weights: {
        Row: {
          id: string
          user_id: string
          date: string
          weight_kg: number
          body_fat_percentage: number | null
          waist_cm: number | null
          hips_cm: number | null
          chest_cm: number | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          weight_kg: number
          body_fat_percentage?: number | null
          waist_cm?: number | null
          hips_cm?: number | null
          chest_cm?: number | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          weight_kg?: number
          body_fat_percentage?: number | null
          waist_cm?: number | null
          hips_cm?: number | null
          chest_cm?: number | null
          notes?: string | null
          created_at?: string
        }
      }
      habits: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          target_value: number | null
          unit: string | null
          icon: string | null
          color: string | null
          is_active: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          target_value?: number | null
          unit?: string | null
          icon?: string | null
          color?: string | null
          is_active?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          target_value?: number | null
          unit?: string | null
          icon?: string | null
          color?: string | null
          is_active?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
      habit_logs: {
        Row: {
          id: string
          habit_id: string
          user_id: string
          date: string
          value: number | null
          completed: boolean | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          habit_id: string
          user_id: string
          date?: string
          value?: number | null
          completed?: boolean | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          habit_id?: string
          user_id?: string
          date?: string
          value?: number | null
          completed?: boolean | null
          notes?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
