// This file will be auto-generated by Supabase CLI
// For now, we define basic types manually

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      exercises: {
        Row: {
          id: string
          name: string
          description: string | null
          muscle_group: string
          equipment: string | null
          video_url: string | null
          is_custom: boolean | null
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          muscle_group: string
          equipment?: string | null
          video_url?: string | null
          is_custom?: boolean | null
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          muscle_group?: string
          equipment?: string | null
          video_url?: string | null
          is_custom?: boolean | null
          created_by?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "exercises_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          }
        ]
      }
      workout_templates: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          type: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          type?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          type?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      workout_exercises: {
        Row: {
          id: string
          workout_id: string
          exercise_id: string
          order_index: number
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          workout_id: string
          exercise_id: string
          order_index: number
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          workout_id?: string
          exercise_id?: string
          order_index?: number
          notes?: string | null
          created_at?: string
        }
      }
      workout_sets: {
        Row: {
          id: string
          workout_exercise_id: string
          set_number: number
          reps: number | null
          weight_kg: number | null
          distance_km: number | null
          duration_seconds: number | null
          rpe: number | null
          created_at: string
        }
        Insert: {
          id?: string
          workout_exercise_id: string
          set_number: number
          reps?: number | null
          weight_kg?: number | null
          distance_km?: number | null
          duration_seconds?: number | null
          rpe?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          workout_exercise_id?: string
          set_number?: number
          reps?: number | null
          weight_kg?: number | null
          distance_km?: number | null
          duration_seconds?: number | null
          rpe?: number | null
          created_at?: string
        }
      }
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          date_of_birth: string | null
          gender: string | null
          height_cm: number | null
          target_weight_kg: number | null
          target_calories: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          date_of_birth?: string | null
          gender?: string | null
          height_cm?: number | null
          target_weight_kg?: number | null
          target_calories?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          date_of_birth?: string | null
          gender?: string | null
          height_cm?: number | null
          target_weight_kg?: number | null
          target_calories?: number | null
          created_at?: string
          updated_at?: string
        }
      }
      workouts: {
        Row: {
          id: string
          user_id: string
          date: string
          name: string | null
          type: string
          duration_minutes: number
          distance_km: number | null
          calories_burned: number | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          name?: string | null
          type: string
          duration_minutes: number
          distance_km?: number | null
          calories_burned?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
           name?: string | null
          type?: string
          duration_minutes?: number
          distance_km?: number | null
          calories_burned?: number | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      meals: {
        Row: {
          id: string
          user_id: string
          date: string
          meal_type: string
          food_name: string
          portion: string | null
          calories: number
          protein_g: number | null
          carbs_g: number | null
          fat_g: number | null
          image_url: string | null
          ai_estimated: boolean | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          meal_type: string
          food_name: string
          portion?: string | null
          calories: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          image_url?: string | null
          ai_estimated?: boolean | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          meal_type?: string
          food_name?: string
          portion?: string | null
          calories?: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          image_url?: string | null
          ai_estimated?: boolean | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      food_database: {
        Row: {
          id: string
          name: string
          category: string | null
          serving_size: string | null
          calories: number
          protein_g: number | null
          carbs_g: number | null
          fat_g: number | null
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          category?: string | null
          serving_size?: string | null
          calories: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          category?: string | null
          serving_size?: string | null
          calories?: number
          protein_g?: number | null
          carbs_g?: number | null
          fat_g?: number | null
          created_at?: string
        }
      }
      weights: {
        Row: {
          id: string
          user_id: string
          date: string
          weight_kg: number
          body_fat_percentage: number | null
          waist_cm: number | null
          hips_cm: number | null
          chest_cm: number | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          weight_kg: number
          body_fat_percentage?: number | null
          waist_cm?: number | null
          hips_cm?: number | null
          chest_cm?: number | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          weight_kg?: number
          body_fat_percentage?: number | null
          waist_cm?: number | null
          hips_cm?: number | null
          chest_cm?: number | null
          notes?: string | null
          created_at?: string
        }
      }
      habits: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          target_value: number | null
          unit: string | null
          icon: string | null
          color: string | null
          is_active: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          target_value?: number | null
          unit?: string | null
          icon?: string | null
          color?: string | null
          is_active?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          target_value?: number | null
          unit?: string | null
          icon?: string | null
          color?: string | null
          is_active?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
      habit_logs: {
        Row: {
          id: string
          habit_id: string
          user_id: string
          date: string
          value: number | null
          completed: boolean | null
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          habit_id: string
          user_id: string
          date?: string
          value?: number | null
          completed?: boolean | null
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          habit_id?: string
          user_id?: string
          date?: string
          value?: number | null
          completed?: boolean | null
          notes?: string | null
          created_at?: string
        }
      }
      todos: {
        Row: {
          id: string
          user_id: string
          date: string
          text: string
          completed: boolean | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          text: string
          completed?: boolean | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          text?: string
          completed?: boolean | null
          created_at?: string
          updated_at?: string
        }
      }
      sleep_logs: {
        Row: {
          id: string
          user_id: string
          date: string
          duration_minutes: number
          quality: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          duration_minutes: number
          quality?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          duration_minutes?: number
          quality?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      daily_journals: {
        Row: {
          id: string
          user_id: string
          date: string
          content: string
          mood: string | null
          energy_level: number | null
          ai_summary: string | null
          ai_insights: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          date?: string
          content: string
          mood?: string | null
          energy_level?: number | null
          ai_summary?: string | null
          ai_insights?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          date?: string
          content?: string
          mood?: string | null
          energy_level?: number | null
          ai_summary?: string | null
          ai_insights?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
